# Configuration for Unsupervised PPE Detection


# -- Workflow and Path Configuration ---
project_root_path: "/content/drive/MyDrive/PPE_Violation_Detection_Project"

# --- Data Source Configuration ---
data_source: "roboflow"
roboflow:
  api_key: "YOUR_ROBOFLOW_API_KEY"
  workspace: "skcet-g4h72"
  project: "construction-ppe-rdhzo"
  version: 3

# -- Project Paths --
data_dir: 'data/'
output_dir: 'output/'
checkpoint_dir: 'output/checkpoints/'

# -- Model Configuration --
model:
  name: 'vit_small_patch14_dinov2'
  pretrained: True
  frozen_layers: 10 # Number of initial transformer blocks to freeze

# -- Training Configuration --
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  optimizer: 'adam'
  resume_training: True # Flag to enable/disable resumable training
  data_fraction: 1.0 # Fraction of data to use for training (1.0 for all data)

# -- Discovery Configuration --
discovery:
  class_map:
    1: 'person'
    2: 'helmet'
    3: 'vest'

# -- Violation Detection --
violation:
  tracker: 'botsort'
